# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15e1607ad4773eea1cadd8f96d2e71234a95ac6d451bfbb24fba4ffae81de0e96fe996d8f51ab75653902c7b9705b25503cab22bb911cff039dd241b911b4d57

test:
  secret_key_base: 66019de59911b9c291d90b667b79f6d15b492338fcedecc7470b458484f42f4b2728510ed17413a62fd66258c0fdba8ffe79a2325058a4cd392d32dfcc6f1989

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
